version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: billionaire-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: billionaire-sim-beta
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - billionaire-network

  redis:
    image: redis:alpine
    container_name: billionaire-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - billionaire-network

  # Optional: Redis Commander for GUI management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: billionaire-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - billionaire-network
    depends_on:
      - redis

  # Optional: Mongo Express for GUI management
  mongo-express:
    image: mongo-express:latest
    container_name: billionaire-mongo-express
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    networks:
      - billionaire-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  billionaire-network:
    driver: bridge 